language: generic

dist: xenial
os: linux

services: 
  - docker

before_install:
  - docker build -t jpablovaz/wopiro-public -f Dockerfile.dev .

script:
  - docker run -e CI=true jpablovaz/wopiro-public npm run test

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: wopiro
  env: "Wopiro-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-811784684892"
  bucket_path: "wopiro"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY