language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t jpablovaz/wopiro-public -f Dockerfile.dev .

script:
  - docker run -e CI=true jpablovaz/wopiro-public npm run test
